services:
  bambu-monitor:
    build: .
    container_name: bambu-monitor
    ports:
      - "8080:8080"
    environment:
      - BAMBU_IP=${BAMBU_IP}
      - BAMBU_SERIAL=${BAMBU_SERIAL}
      - BAMBU_ACCESS_CODE=${BAMBU_ACCESS_CODE}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - TG_CHAT_ID=${TG_CHAT_ID}
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
