{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  {{- range $key, $val := .Values.config }}
  {{- if or (kindIs "map" $val) (kindIs "slice" $val) }}
  {{ $key }}: {{ $val | toJson | quote }}
  {{- else }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  {{- range $key, $val := .Values.secret }}
  {{- if or (kindIs "map" $val) (kindIs "slice" $val) }}
  {{ $key }}: {{ $val | toJson | b64enc | quote }}
  {{- else }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
