apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name }}-health
  labels:
     app: {{.Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: health
      protocol: TCP
      name:  health
  selector:
    app: {{.Release.Name }}


