secret:
    BAMBU_IP: ENC[AES256_GCM,data:15EtI6zgbozy3cNg,iv:PT/1hpbbM8mPJrWJqeNOnJ0bvenma2ut2CU7stHgSw4=,tag:TVEt3an7JgbuOKzgxDuXuA==,type:str]
    BAMBU_SERIAL: ENC[AES256_GCM,data:eftemxXVzzS7KUZNIluk,iv:cQ2M3zT1y/ioV9EQOOdmtNesMZQDFDd0P1Le6P9Nl0s=,tag:emjR9Nk7hKsPefw138u6gQ==,type:str]
    BAMBU_ACCESS_CODE: ENC[AES256_GCM,data:men2MypvZVo=,iv:YUv/z+ab34/UL5vA0lVLs1w1Jy7NLo1uSf7FZd9jcqM=,tag:3DstflowlgclRKBUiNnxNg==,type:str]
    TG_BOT_TOKEN: ENC[AES256_GCM,data:ySSvsYOzDz7GPZ71I1rGQN+lcuAZnS4ouNxnnn6qMT6jJYQrGnS647WrJrh4GA==,iv:pvtpKlDGAG8cImjHryvWPoPBqYEwK0AQ7735r4JFE9Q=,tag:mg3a9hSPinqhDfQqGvxFyQ==,type:str]
    TG_CHAT_ID: ENC[AES256_GCM,data:t7/ibxs/Eo01Nyk=,iv:PhhZ5AlOSGc3jvAGriB2GWLd4YZeZHMXujDzbNg66Z8=,tag:vZ2v0Ip+0esjx/L5GCI6yA==,type:str]
    DDD: ENC[AES256_GCM,data:TX5x,iv:hOYBMIvGND3BCdBiQ6H5pxo1oGBIwJGRp28HA8IEZ8Y=,tag:kYu+BMToVWBSP8jF3BbOpQ==,type:str]
sops:
    age:
        - recipient: age1rms68a5t3a2g5ayfjfysvewahqrrmap9r9rxgna4kfj79lx5af4sg4ms2a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMR1ZxVTdkeW9LeWdVM25Y
            VGxhMkhFbzNxWFFoQ2ROVEJyRTFIQUF2U0g4CldGaW1abklrcFAvRy93dVdtVGpq
            WkcvMkhUcitpUys2NDliTGZPdUtXVlEKLS0tIHk0aSsrYmdaWUtnSmZmWVRJZzI1
            d2ZXWDBhREZhWjJQMndic2FMekhaSkEKCvFDF3ehy6ArN2yODo+jESrXEVQ1SwDu
            21tuhcQoKIYmwvkSfWf9L+g1slZIYZZ5069NYW0FQj7ZETKbT2r/iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T16:36:28Z"
    mac: ENC[AES256_GCM,data:fEM3XyCRdsAx7qfocPhGpIrwGGs5L3DwyY12Mr00vaDiVkBh3p9+6aULXv+4wxwUfmfAo68sBwdezkOgL+e7RL0J84805P0Z/QgZ1pZPm3+4drkszNTxkxw2N1O1Errz/4XgikjxUbvju3h2UDx3yCxaQ7dZkvtIeKK9QHgeUTo=,iv:RSY7Nds9Zq3nP+fFDMR2PWbD9d9jrdN8yP8fMl8gYFw=,tag:nm0nTlDAiJ4WNyF6/JmilQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
