imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

image:
  repository: docker.io/rooibos75
  name: bambu-monitor
  tag: dev-12
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi

securityContext: 
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10101
